### ISSUE TITLE
‼️ Note that Ultradom was originally Picodom ‼️

### ISSUE THREAD

**Issue by brodybits** [jorgebucaran/ultradom#101]
I saw a note that Picodom was renamed to Patchdom but not that it was then renamed to ultradom, was confused by "Ultradom" reference in <https://github.com/hyperapp/hyperapp/issues/632#issuecomment-370461629>. A note in README.md would be nice, I think.

**Comment by JSteunou** [comment]
I also had hard time to follow, glad to find my way back to this repo :D
