### ISSUE TITLE
Asynchronously Removing Elements

### ISSUE THREAD

**Issue by pickle-ts** [jorgebucaran/ultradom#107]
I'm using ultradom with animation. To make exit animations work, elements need to be asynchronously removed from the DOM. In other words, there's a delay between remove and destroy, where the vdom may get updated during that delay. To handle that scenario, I had to make the following change to the vdom algorithm to maintain integrity of the DOM:

```
// before removing an element (but before its destroyed), mark element as such:

element["removing"] = true

// ... and then when patching:

var active = Array.from (node.childNodes).filter(x => x["removing"] !== true) // consider perf + browser support
for (var i = 0; i < oldChildren.length; i++) {
   oldElements[i] = active[i]

```
Otherwise the patcher will assume a future state of the real DOM that may not yet have been realised (since async operations may not yet have completed). The patcher will then try to match up virtual elements with real DOM elements, where some of those real DOM elements need to be ignored because they should no longer exist as far as the patcher is concerned (i.e. its reconciliation phase is over; the patcher only cares about the old elements for the purpose of cleanup & firing destroyed events).

Have I understood this correctly, or is there something I've got wrong? Thanks for your time.

Cheers

**Comment by jorgebucaran** [comment]
@pickle-ts Hmm, I don't understand what you are trying to do? 

Did you read [this](https://github.com/jorgebucaran/ultradom#onremove)? or is this related to https://github.com/jorgebucaran/ultradom/issues/68?

**Comment by pickle-ts** [comment]
When an element is removed (ultimately in response to the model changing), I'm intercepting the onremove callback to provide an exit animation.

Just scanned through issue #68; it's highly related.

I'll need to spend more time understanding the patching algorithm to work out whether the fix I've proposed works in the general case.

**Comment by jorgebucaran** [comment]
Thanks, @pickle-ts! If you find out whether this is the same as #68, then let's close either of those issues to track the problem in only one place.

**Comment by jorgebucaran** [comment]
https://github.com/jorgebucaran/ultradom/releases/tag/3.0.0 🎉
