### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/ultradom#109]
This is more of a suggestion for source code organization. How about moving all the helper files into a subfolder that patch imports? Would make for a cleaner repository structure:

```
--|utls
--|--clone.js
--|--createElement.js
--|--eventListener.js
--|--getKey.js
--|--patchElement.js
--|--recycleElement.js
--|--removeChildren.js
--|--removeElement.js
--|--updateAttribute.js
--|--updateElement.js
--h.js
--index.js
--patch.js
```

And update `patch.js` to import its dependencies like this:

```javascript
import { recycleElement } from "./utils/recycleElement"
import { patchElement } from "./utils/patchElement"
```

**Comment by jorgebucaran** [comment]
🤔

**Comment by rbiggs** [comment]
Anyways, if [#108](https://github.com/jorgebucaran/ultradom/issues/108) happens, this wouldn't be necessary.

**Comment by jorgebucaran** [comment]
Still not sure what I am going to do about this. I often change my mind inexplicably, so I may reconsider this in the future. I don't see any use of keeping this issue open since this is not an actual problem so closing. Thanks for the suggestion @rbiggs!

**Comment by rbiggs** [comment]
The only issue that matters right now any ways is Hyperapp 2.0 #672. ;-)
