### ISSUE TITLE
Issue with oncreate being called too early

### ISSUE THREAD

**Issue by Wildhoney** [jorgebucaran/ultradom#110]
In my code I have the following snippet:

```javascript
const root = patch(tree, previous && previous.root);
!previous && props.boundary.appendChild(root);
```

What I want to do is to render into the shadow boundary, however that doesn't seem to work after switching over to `ultradom`. I found a workaround where I simply `patch` with the second argument as `undefined` initially, and then append the `root` to the boundary. On second render we use the `previous.root` which I memorise, which diffs the two DOM states and patches accordingly.

All's good well until I introduce an `oncreate` callback into the JSX. It looks as though the `oncreate` handler is invoked during the `patch` rather than when the node is actually in the DOM. I can verify this by doing:

```html
<dialog open oncreate={e => console.log(e.isConnected)} />
```

Which yields `false`, and only in the next *tick* does it become `true`.

Do you have any idea where the actual problem lies? Should I be focussing on rendering into the shadow boundary in the `patch`, or should the `oncreate` actually determine if the node is in the DOM before invoking the callback &ndash; maybe using `MutationObserver`?

**Comment by Wildhoney** [comment]
The issue is also apparent in the example taken from the README:

```javascript
import { h, patch } from "ultradom"

const oncreate = n => console.log(n.isConnected);

const view = count =>
  h("div", {}, [
    h("h1", {}, count),
    h("button", { oncreate, onclick: () => patch(view(count - 1), element) }, "-"),
    h("button", { oncreate, onclick: () => patch(view(count + 1), element) }, "+")
  ])

const element = document.body.appendChild(patch(view(0)))
```

Whereas in the README it also claims:

> This event is fired after the element is created and attached to the DOM.

**Comment by jorgebucaran** [comment]
> @Wildhoney oncreate handler is invoked during the patch...

oncreate is invoked inside `patch`, but **after** `patchElement`. We add it to a queue first:

https://github.com/jorgebucaran/ultradom/blob/1c43374fcb3d133341f00288ac677158adf5dd70/src/createElement.js#L13-L17

...then flush it after the DOM is patched.

https://github.com/jorgebucaran/ultradom/blob/1c43374fcb3d133341f00288ac677158adf5dd70/src/patch.js#L20

> The `oncreate` event is fired after the element is created and attached to the DOM.

In Ultradom you are responsible for adding the element to the DOM yourself (unless you pass an element as the second argument) — in Hyperapp you always provide the container, so the `oncreate` documentation is definitely true over there.

I think we need to modify Ultradom's API again to match how it works in Hyperapp.

**Comment by Wildhoney** [comment]
I think maybe it's just a case of updating the documentation to make it clear. There's no guarantee that when `oncreate` is invoked that the element is in the DOM. It depends how you invoke `patch`:

* If no `element` is provided then `oncreate`'s `isConnected` will be `false` as you `appendChild` after `patchElement`.
* If `element` is provided but its `isConnected` is `false` then `oncreate`'s `isConnected` will be `false` too.
* Otherwise `true`.

I changed my code a little to append an empty element to my shadow boundary, and then instructed `ultradom` to use that as the `element` which seems to work well:

```javascript
const initialRoot = !previous && document.createElement(tree.nodeName);
initialRoot && props.node.shadowRoot.appendChild(initialRoot);
const root = patch(tree, previous ? previous.root : initialRoot);
```

In that scenario I can guarantee that `oncreate` will be invoked with the elements in the DOM.

I think a README update would suffice, rather than changing the API? Even in `picodom` with its old style API, I imagine the second point from above (if `element` is provided...) would still have been an issue, because you could quite easily have provided an element that wasn't in the DOM and it would have been patched without any complaints.

**Comment by jorgebucaran** [comment]
@Wildhoney I am not sure how to update the documentation.

Would the following API be problematic for you? Just curious.

```js
patch(container, oldNode, newNode)
```

**Comment by Wildhoney** [comment]
It shouldn't be an issue because that's similar to how `ultradom` had it.

However, I'm not sure it *should* be changed for the sole reason of calling `oncreate` when the element is in the DOM, as even with the above change to the `patch` function, there's still no guarantee it's in the DOM.

By using my approach of `patch(tree, previous ? previous.root : initialRoot)` I can prevent the issue whereby the element isn't in the DOM yet because I `appendChild` later.

**Comment by jorgebucaran** [comment]
@Wildhoney Well, there's guarantee it will be _in_ the `container` no?

**Comment by Wildhoney** [comment]
Yes, there's that guarantee with my change and with the proposed `patch` change.

**Comment by Wildhoney** [comment]
As I see it, the `patch` change is unnecessary because I can achieve the same with:

```javascript
const initialRoot = !previous && document.createElement(tree.nodeName);
initialRoot && props.boundary.appendChild(initialRoot);
const root = patch(tree, previous ? previous.root : initialRoot);
```

As the above `appendChild` happens **before** the `patch`, whereas in the README it's showing the `appendChild` **after**. For me, I know `initialRoot` is in the DOM, and so I expect `x.isConnected` to be `true`, which it is.

Whether we use the above code or change `patch` to the old style, the guarantee is the same &ndash; as long as `container` is in the DOM, `oncreate` will be invoked with `x.isConnected` to `true`.

By using the example in the README `x.isConnected` will **always** be `false` because the `appendChild` occurs after the `patchElement`. With the `patch` the way it is, we've made the `isConnected` issue more complex, but that's not necessarily a *bad* thing.

For those reasons I think the API should change as-is, but we may need to update the README.

Aside: I didn't actually notice the issue initially, because in most cases it doesn't matter whether `oncreate` is invoked when the element is in the DOM or not &ndash; I can still manipulate it and have those changes reflected in the DOM when it is appended. However, when I tried to use the `dialog` element, I wanted to invoke `dialog.showModal()` which is only allowed when `dialog` is in the DOM, and not before. I needed that guarantee.

**Comment by jorgebucaran** [comment]
@Wildhoney How would you like me to change the README?

**Comment by jorgebucaran** [comment]
@Wildhoney https://github.com/jorgebucaran/ultradom/releases/tag/3.0.0

You can't no longer target a specific element to update, but only specify a container, so oncreate is guaranteed to run when the element already exists in the container.
