### ISSUE TITLE
Add support for JSX fragments

### ISSUE THREAD

**Issue by mindplay-dk** [jorgebucaran/ultradom#71]
[JSX fragments](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) are a thing now - we should add support for this.

Note @JorgeBucaran: since you're planning to rewrite the diff algo, I'd suggest writing it with fragments in mind - that is, work from the assumption that everything is a set. It's generally simpler/easier to work from the assumption of zero-or-more sets of (V)Nodes than dealing conditionally with nulls. (I tried to work from that assumption in my own rewrite, where, internally, the patch operation works with sets, and the public patch-function starts by dealing with null by turning it into an empty set, so that the internal algo doesn't need to deal with nulls at all.)

**Comment by JorgeBucaran** [comment]
@mindplay-dk Hmm, not really sure I'd want this at all.

**Comment by mindplay-dk** [comment]
It enables you to implement functional components that return a range of elements - in other words, you're not longer forced to start every component with a (sometimes dummy) wrapper element.

Anyways, it's what JSX is now - it's already supported both by Babel and Typescript.

**Comment by mindplay-dk** [comment]
It's definitely low on my wishlist though - the critical thing (IMO) is sorting out the life-cycle events. Once that's done, I can actually start building my app with this 😄

**Comment by JorgeBucaran** [comment]
> @mindplay-dk It enables you to implement functional components that return a range of elements - in other words, you're not longer forced to start every component with a (sometimes dummy) wrapper element.

We can create components that return a range of elements already!

```js
const MyList = props => [<p>A</p>, <p>B</p>, <p>C</p>]
```

What we don't currently support is patching a root node that it itself is an array.

**Comment by mindplay-dk** [comment]
> We can create components that return a range of elements already!

I know, but that's kind of ugly, and it's not how the JSX community wants to do it.

> What we don't currently support is patching a root node that it itself is an array.

React also does not support that, as far as I know - the point of JSX fragments, if I understand correctly, is merely to be able to create a range of elements using XML-like JSX syntax, without having to wrap it in braces and brackets.

Anyhow, as said, this is definitely not a high priority for me, personally - but the community has decided they want this, and it's likely not much work to support it, especially if you factor your new implementation so it consistently operates on sets.

I'm *much* more interested in solving the ordering issues, for one :-)

**Comment by JorgeBucaran** [comment]
You mean the community would prefer to rewrite my example as 😮 

```jsx
const MyList = props =>
  </>
    <p>A</p>
    <p>B</p>
    <p>C</p>
  </>
```
?

**Comment by JorgeBucaran** [comment]
@mindplay-dk Okay, let's keep this open and see what happens. :)

**Comment by mindplay-dk** [comment]
> ?

Apparently, yeah 😆

**Comment by Pyrolistical** [comment]
the syntax is
```
const MyList = props =>
  <>
    <p>A</p>
    <p>B</p>
    <p>C</p>
  </>
```

and the main advantage is text nodes. people rather write `<>hello<hr/></>` over `['hello', <hr/>]`

**Comment by JorgeBucaran** [comment]
@Pyrolistical What does it compile to?

**Comment by Pyrolistical** [comment]
i don't understand your question, `<>hello<hr/></>` compiles to the same thing as `['hello', <hr/>]`

**Comment by JorgeBucaran** [comment]
Well, that answers the question. Thanks!

**Comment by JorgeBucaran** [comment]
If that's **true**, then we already support the syntax.

**Comment by Pyrolistical** [comment]
Apparently in order to support this you need to expose a function and set it to paramFrag

https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-jsx/README.md

**Comment by jorgebucaran** [comment]
Yeah, but that's just one part. In order to support this createElement and patch must be modified also to process fragments. This functionality is coming to Hyperapp someday, after 2.0 and other priorities are sorted out, but not to Ultradom.
